### ISSUE TITLE
Attendee profile

### ISSUE THREAD

**Issue by DSalko** [eventbrite/eventbrite-sdk-ruby#14]
Hello

I have noticed that `Attendee` profile returns `home_phone` but doesn't return `cell_phone` ( when cell_phone exists for attendee ).

Anyone else had the same issue?

thanks.

**Comment by vinnie-eb** [comment]
Hi dsalko,

I'd love to help you, but profile info is not defined by the SDK, that comes directly from v3. Please save issues for features, or bug fixes for the ruby SDK itself.

**Comment by DSalko** [comment]
Yes, you are right, there is no definition here for profile fields. Sorry for this.

**Comment by vinnie-eb** [comment]
No worries, thanks!
