### ISSUE TITLE
Transfer tickets from one owner to another.

### ISSUE THREAD

**Issue by Webern** [eventbrite/eventbrite-sdk-ruby#16]
Is it possible to use the API to transfer the ownership of a ticket from one person to another?

**Comment by jeff-eb** [comment]
No, sorry. There's nothing in the API that provides for this. There are read only endpoints for event attendees but no way to edit them.

https://www.eventbrite.com/developer/v3/endpoints/events/#ebapi-get-events-id-attendees-attendee-id

For API specific questions like this it's best to check out the [API support](https://www.eventbrite.com/developer/v3/resources/support/ ) page which has links to the public Google forum as well as a form for getting developer support. This repo is for supporting the actual gem that provides API interaction.
