### ISSUE TITLE
Getting swarmed with ticket_class.created webhook events

### ISSUE THREAD

**Issue by WayneUong** [eventbrite/eventbrite-sdk-ruby#28]
We're getting hundreds of `ticket_class.created` webhook events per hour. It only started this afternoon. We've been running fine for a few months now, can't really think of any reason that they're coming from our end. Anyone experiencing this?

**Comment by vinnie-eb** [comment]
Hi @WayneUong,

Thanks for writing in. Unfortunately, we are unable to assist you with v3 issues. This repo is for the Ruby SDK, not the v3 API. 

Here's support for the v3 API: https://www.eventbrite.com/developer/v3/resources/support/

Thanks!
