### ISSUE TITLE
Improve documentation about how to list objects

### ISSUE THREAD

**Issue by lichtamberg** [eventbrite/eventbrite-sdk-ruby#31]
I tried to find out how I can list objects which are not related to another object, f.e. webhooks?
I just want a list of all webhooks f.e.?

Would be great if you could document this.

**Comment by vinnie-eb** [comment]
Hi @lichtamberg! Thanks for the feedback, I'll work on adding `Operations::List` to the webhooks resource, and I'll add the documentation on how to fetch it. As an example `Category.list` is how one would retrieve shallow url objects.
